# Generated by Django 5.1.6 on 2025-02-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorhunt_app', '0002_doctor_medicalrecord_patient_medicalrecord_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('tests_offer', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('services', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
